const C=document.querySelector('#scope'),g=C.getContext('2d'),txt=document.querySelector('#text'),play=document.querySelector('#play'),preset=document.querySelector('#preset'),rate=document.querySelector('#rate'),depth=document.querySelector('#depth'),seed=document.querySelector('#seed');
let ac,master,src,playing=false,phase=0,start=0,rng=Math.random,noise=1,hit=0;
function randomSeed(){let s=(Date.now()^Math.random()*2**31)|0;rng=()=>{s|=0;s=s+0x6D2B79F5|0;let t=Math.imul(s^s>>>15,1|s);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function shape(P,t,d,r){let a=t*6.283,x=0,y=0;if(P==='ROSETTE'){let q=.55+.35*Math.sin(4*a);x=q*Math.cos(a);y=q*Math.sin(a)}else if(P==='KNOT'){x=.68*Math.sin(3*a)+.22*Math.sin(7*a);y=.68*Math.sin(2*a+.7)+.2*Math.sin(5*a)}else if(P==='SPIRAL'){let q=.08+.82*t;x=q*Math.cos(a*(4+3*d));y=q*Math.sin(a*(4+3*d))}else if(P==='BUTTERFLY'){let q=.42+.25*Math.sin(2*a)+.12*Math.sin(6*a);x=q*Math.sin(a)*1.35;y=q*Math.cos(a)}else if(P==='GEAR'){let q=.58+.16*Math.cos((6+Math.floor(d*6))*a);x=q*Math.cos(a);y=q*Math.sin(a)}else if(P==='ORBIT'){x=.62*Math.sin(2*a)+.25*Math.sin(5*a+.4);y=.62*Math.cos(3*a)+.2*Math.sin(4*a)}else if(P==='WEAVE'){x=.7*Math.sin(3*a)+.16*Math.sin(11*a);y=.7*Math.sin(4*a+.4)+.16*Math.sin(9*a)}else{x=.55*Math.sin(3*a+1.3*Math.sin(5*a))+d*.2*Math.sin(13*a);y=.55*Math.sin(4*a+1.1*Math.sin(2*a))+d*.2*Math.cos(11*a)}return[x,y]}
const glyphs={N:[[-.8,.7],[-.8,-.7],[-.8,.7],[.8,-.7],[.8,.7]],O:[[.7,0],[.5,.6],[-.5,.6],[-.7,0],[-.5,-.6],[.5,-.6],[.7,0]],I:[[0,.7],[0,-.7]],S:[[.7,.55],[0,.7],[-.65,.4],[-.45,.05],[.45,-.05],[.65,-.4],[0,-.7],[-.7,-.55]],E:[[.7,.7],[-.7,.7],[-.7,-.7],[.7,-.7],[-.7,-.7],[-.7,0],[.45,0]],Z:[[-.7,.7],[.7,.7],[-.7,-.7],[.7,-.7]],A:[[-.7,-.7],[0,.7],[.7,-.7],[.4,-.1],[-.4,-.1]],P:[[-.65,-.7],[-.65,.7],[.35,.7],[.65,.4],[.35,.05],[-.65,.05]],L:[[-.65,.7],[-.65,-.7],[.7,-.7]],V:[[-.7,.7],[0,-.7],[.7,.7]],T:[[-.7,.7],[.7,.7],[0,.7],[0,-.7]],D:[[-.65,-.7],[-.65,.7],[.2,.7],[.7,.3],[.7,-.3],[.2,-.7],[-.65,-.7]],R:[[-.65,-.7],[-.65,.7],[.3,.7],[.65,.35],[.3,0],[-.65,0],[.2,0],[.7,-.7]]};
function wordPoints(word){let out=[],chars=[...word],cw=1.7,total=chars.length*cw;chars.forEach((ch,j)=>{let q=glyphs[ch]||glyphs.I;for(let i=0;i<q.length-1;i++){let a=q[i],b=q[i+1],steps=18;for(let k=0;k<steps;k++){let u=k/steps;out.push([(j*cw-total/2+a[0]*.65+(b[0]-a[0])*.65*u)/(total*.58),(a[1]+(b[1]-a[1])*u)*.55])}}});return out}
const words=['NOISE','SPIKE','SLOPE','ZAP','IMPULSE','COIL','FOLD','DECAY'];
function comp(s,t){let bar=Math.floor(t/2)%16,p=t%2,a=p*6.283,x=0,y=0,env=Math.exp(-p*8);if((bar%2)===1){let pts=wordPoints(words[Math.floor(bar/2)]),u=Math.floor((p/2)*pts.length)%pts.length;return pts[u]||[0,0]};if(bar<2){x=(rng()-.5)*.12;y=(rng()-.5)*.12}else if(bar<4){x=.7*Math.sin(a*7)*env;y=.7*Math.sin(a*9+.8)*env}else if(bar<6){let q=p;x=(q*2-1)*.8;y=.65-(q*1.3)}else if(bar<8){x=.75*Math.sin(a*13)*env;y=(rng()-.5)*.5*env}else if(bar<10){x=(p<.08?.85*Math.sin(a*35):0)+(rng()-.5)*.08;y=(p<.08?.8*Math.cos(a*29):0)}else if(bar<12){let q=.15+.7*p;x=q*Math.cos(a*5);y=q*Math.sin(a*5)}else if(bar<14){x=.65*Math.sin(a*3+Math.sin(a*11));y=.65*Math.sin(a*4)}else{x=(rng()-.5)*.7*env;y=(rng()-.5)*.7*env}return[x,y]}
function build(){if(!ac)return;if(src)src.disconnect();let node=ac.createScriptProcessor(1024,0,2),sr=ac.sampleRate;node.onaudioprocess=e=>{let L=e.outputBuffer.getChannelData(0),R=e.outputBuffer.getChannelData(1);for(let i=0;i<L.length;i++){let P=preset.value,r=+rate.value,d=+depth.value,[x,y]=P==='COMPOSITION'?comp(0,ac.currentTime-start+i/sr):shape(P,phase,d,r);if(P!=='COMPOSITION')phase=(phase+(38+r*70)/sr)%1;L[i]=x*.38;R[i]=y*.38}};node.connect(master);src=node}
function init(){ac=new AudioContext();master=ac.createGain();master.gain.value=0;master.connect(ac.destination);randomSeed();start=ac.currentTime;build()}
play.onclick=async()=>{if(!ac)init();await ac.resume();playing=!playing;if(playing&&preset.value==='COMPOSITION')start=ac.currentTime;master.gain.setTargetAtTime(playing?.7:0,ac.currentTime,.015);play.textContent=playing?'STOP':'PLAY'};preset.onchange=()=>{if(ac){start=ac.currentTime;build()}};seed.onclick=()=>{randomSeed();phase=rng();if(ac){start=ac.currentTime;build()}};
function draw(){requestAnimationFrame(draw);let d=devicePixelRatio||1,w=C.clientWidth,h=C.clientHeight;if(C.width!==w*d||C.height!==h*d){C.width=w*d;C.height=h*d}g.setTransform(d,0,0,d,0,0);g.fillStyle='#0a0c0a';g.fillRect(0,0,w,h);g.strokeStyle='#202720';g.beginPath();g.moveTo(w/2,0);g.lineTo(w/2,h);g.moveTo(0,h/2);g.lineTo(w,h/2);g.stroke();let P=preset.value,N=1600,T=ac?ac.currentTime-start:0;g.strokeStyle='#b7c8b1';g.lineWidth=1.1;g.beginPath();for(let i=0;i<=N;i++){let t=i/N,[x,y]=P==='COMPOSITION'?comp(0,T+(t-.5)*.08):shape(P,t,+depth.value,+rate.value);let X=w/2+x*w*.43,Y=h/2-y*h*.43;i?g.lineTo(X,Y):g.moveTo(X,Y)}g.stroke();if(P==='COMPOSITION'&&playing){let bar=Math.floor(T/2)%16,n=['NOISE / 00','SPIKE / 01','SLOPE / 02','ZAP / 03','IMPULSE / 04','COIL / 05','FOLD / 06','DECAY / 07'][Math.floor(bar/2)];let phrases=['SIGNAL LOST','NO CARRIER','DO NOT ADJUST','VOLTAGE DROP','PACKET ERROR','ARC DETECTED','PHASE UNSTABLE','END OF LINE'];let k=Math.floor(bar/2);txt.textContent=''}else txt.textContent=''}draw();