const C=document.querySelector('#scope'),g=C.getContext('2d'),play=document.querySelector('#play'),editor=document.querySelector('#score'),mutate=document.querySelector('#random'),status=document.querySelector('#status');let ac,master,node,playing=false,start=0,bpm=176,events=[],rng=Math.random;
function seed(){let s=(Date.now()^Math.random()*2**31)|0;rng=()=>{s|=0;s=s+0x6D2B79F5|0;let t=Math.imul(s^s>>>15,1|s);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const G={N:[[-.8,.7],[-.8,-.7],[-.8,.7],[.8,-.7],[.8,.7]],O:[[.7,0],[.5,.7],[-.5,.7],[-.7,0],[-.5,-.7],[.5,-.7],[.7,0]],I:[[0,.7],[0,-.7]],S:[[.7,.6],[0,.7],[-.7,.4],[-.4,0],[.5,-.1],[.7,-.5],[0,-.7],[-.7,-.55]],E:[[.7,.7],[-.7,.7],[-.7,-.7],[.7,-.7],[-.7,0],[.45,0]],R:[[-.7,-.7],[-.7,.7],[.3,.7],[.7,.35],[.3,0],[-.7,0],[.2,0],[.7,-.7]],A:[[-.7,-.7],[0,.7],[.7,-.7],[.4,-.1],[-.4,-.1]],V:[[-.7,.7],[0,-.7],[.7,.7]],L:[[-.7,.7],[-.7,-.7],[.7,-.7]],T:[[-.7,.7],[.7,.7],[0,.7],[0,-.7]],D:[[-.7,-.7],[-.7,.7],[.15,.7],[.7,.3],[.7,-.3],[.15,-.7],[-.7,-.7]],G:[[-.6,.5],[0,.7],[.65,.4],[.65,-.6],[-.2,-.7],[-.7,-.2],[-.55,.45]],P:[[-.7,-.7],[-.7,.7],[.25,.7],[.65,.35],[.25,0],[-.7,0]]};
function textPts(w){let o=[],cs=[...w.replace(/[^A-Z]/g,'')],cw=1.5,tot=Math.max(1,cs.length*cw);cs.forEach((ch,j)=>{let q=G[ch]||G.I;for(let i=0;i<q.length-1;i++)for(let k=0;k<10;k++){let u=k/10,a=q[i],b=q[i+1];o.push([(j*cw-tot/2+(a[0]+(b[0]-a[0])*u)*.55)/(tot*.55),(a[1]+(b[1]-a[1])*u)*.5])}});return o}
function expand(s){s=s.replace(/#.*$/gm,'');let m=s.match(/@(\d+)/);if(m)bpm=Math.max(40,Math.min(400,+m[1]));s=s.replace(/@\d+|grid\s+\d+/g,'');for(let z=0;z<5;z++)s=s.replace(/\[([^\[\]]+)\]\*(\d+)/g,(_,a,n)=>Array(Math.min(32,+n)).fill(a).join(' '));return s.match(/"[^"]+"|\?\d+|[a-z0-9]+/gi)||[]}
function compile(){let t=expand(editor.value),prob=100,o=[];for(let x of t){if(x[0]==='?'){prob=+x.slice(1);continue}if(rng()*100<=prob)o.push(x.toLowerCase());prob=100}events=o.length?o:['spike'];status.textContent=bpm+' BPM · '+events.length}
function proj(x,y,z,t){let ca=Math.cos(t*.7),sa=Math.sin(t*.7),X=x*ca-z*sa,Z=x*sa+z*ca+2.5,k=1.15/Math.max(.45,Z);return[X*k,y*k]}
function voice(n,p,t=0){let a=p*Math.PI*2,e=Math.exp(-p*9),x=0,y=0;if(n[0]==='"'){let q=textPts(n.slice(1,-1).toUpperCase()),i=Math.floor(p*q.length*6)%q.length;return q[i]||[0,0]}if(n==='spike'){x=Math.sin(a*41)*e;y=Math.cos(a*31)*e}else if(n==='zap'){x=Math.sin(a*(10+55*(1-p)))*e;y=Math.sin(a*(17+70*(1-p))+.8)*e}else if(n==='noise'||n==='random'){x=(rng()*2-1)*e;y=(rng()*2-1)*e}else if(n==='crack'){x=Math.sign(Math.sin(a*9))*e;y=(rng()*2-1)*e}else if(n==='slope'){x=p*1.8-.9;y=.8-p*1.6}else if(n==='pulse'){x=Math.sign(Math.sin(a*5))*.8*e;y=Math.sign(Math.sin(a*7))*.8*e}else if(n==='sine'||n==='wave'){x=p*1.8-.9;y=.72*Math.sin(a*3)}else if(n==='coil'||n==='zoomcircle'){let r=n==='zoomcircle'?.05+.9*p:.15+.7*p;x=r*Math.cos(a*7);y=r*Math.sin(a*7)}else if(n==='ring'||n==='rings'){let r=n==='rings'?.25+.55*(Math.floor(p*8)%3)/3:.72;x=r*Math.cos(a*8);y=r*Math.sin(a*8)}else if(n==='knot'){x=.65*Math.sin(a*3)+.2*Math.sin(a*7);y=.65*Math.sin(a*2+.5)+.2*Math.sin(a*5)}else if(n==='fold'||n==='morph'){let m=n==='morph'?p:1;x=.75*Math.sin(a*3+m*2*Math.sin(a*9));y=.72*Math.sin(a*(4+m*2))}else if(n==='checker'){let q=Math.floor(p*64),ix=q%8,iy=Math.floor(q/8);x=(ix/7-0.5)*1.6;y=(iy/7-0.5)*1.6;if(q&1)y+=.09}else if(n==='grid'||n==='lattice'){let q=Math.floor(p*20),u=(p*20)%1;if(q<10){x=-.8+q*.18;y=-.8+u*1.6}else{x=-.8+u*1.6;y=-.8+(q-10)*.18}}else if(n==='grid3d'||n==='cube'||n==='tunnel'){let q=Math.floor(p*24),u=(p*24)%1,z0=(q%4)*.5-.75,X=(q%6<3?u*1.6-.8:(q%3-.5)*.8),Y=(q%6<3?(q%3-.5)*.8:u*1.6-.8);[x,y]=proj(X,Y,z0,t+(n==='tunnel'?p*2:0))}else if(n==='sphere'){let v=p*18,lat=(Math.floor(v)%6-2.5)*.32,u=v%1,th=u*6.283,r=Math.cos(lat);[x,y]=proj(r*Math.cos(th),Math.sin(lat),r*Math.sin(th),t)}else if(n==='landscape'||n==='terrain'||n==='horizon'){x=p*1.8-.9;let f=n==='terrain'?7:3;y=.28*Math.sin(x*f*3+t*2)+.16*Math.sin(x*13-t)+(n==='horizon'?.18:0)}else if(n==='swarm'){let q=Math.floor(p*40);x=.65*Math.sin(q*12.989+t)+.12*Math.sin(a*13);y=.65*Math.sin(q*7.31-t*.7)+.12*Math.cos(a*17)}else{x=.7*Math.sin(a*5);y=.7*Math.cos(a*7)}return[x,y]}
function at(t){let dur=60/bpm/4,i=Math.floor(t/dur),p=((t%dur)+dur)%dur/dur,n=events[((i%events.length)+events.length)%events.length];return voice(n,p,t)}
function build(){if(node)node.disconnect();node=ac.createScriptProcessor(512,0,2);let sr=ac.sampleRate;node.onaudioprocess=e=>{let L=e.outputBuffer.getChannelData(0),R=e.outputBuffer.getChannelData(1),b=ac.currentTime-start;for(let i=0;i<L.length;i++){let [x,y]=at(b+i/sr);L[i]=Math.max(-1,Math.min(1,x*.43));R[i]=Math.max(-1,Math.min(1,y*.43))}};node.connect(master)}
function init(){ac=new AudioContext();master=ac.createGain();master.gain.value=0;master.connect(ac.destination);seed();compile();start=ac.currentTime;build()}
play.addEventListener('click',async()=>{if(!ac)init();await ac.resume();playing=!playing;if(playing)start=ac.currentTime;master.gain.setTargetAtTime(playing?.72:0,ac.currentTime,.01);play.textContent=playing?'STOP':'PLAY'});editor.addEventListener('input',()=>{compile();if(ac)start=ac.currentTime});mutate.addEventListener('click',()=>{seed();let a=['spike','zap','noise','crack','slope','pulse','sine','coil','ring','knot','fold','morph','checker','grid','grid3d','sphere','tunnel','landscape','terrain','swarm','zoomcircle'];editor.value='@'+(150+Math.floor(rng()*90))+'\n['+Array.from({length:12},()=>a[Math.floor(rng()*a.length)]).join(' ')+']*2\n"'+['NOISE','ERROR','VOLTAGE','SIGNAL'][Math.floor(rng()*4)]+'"\n'+Array.from({length:10},()=>a[Math.floor(rng()*a.length)]).join(' ');compile();if(ac)start=ac.currentTime});
function draw(){requestAnimationFrame(draw);let d=devicePixelRatio||1,w=C.clientWidth,h=C.clientHeight;if(C.width!==w*d||C.height!==h*d){C.width=w*d;C.height=h*d}g.setTransform(d,0,0,d,0,0);g.fillStyle='#060806';g.fillRect(0,0,w,h);g.strokeStyle='#171d17';g.lineWidth=1;for(let i=1;i<6;i++){g.beginPath();g.moveTo(w*i/6,0);g.lineTo(w*i/6,h);g.stroke();g.beginPath();g.moveTo(0,h*i/6);g.lineTo(w,h*i/6);g.stroke()}let T=ac?ac.currentTime-start:0;g.strokeStyle='#cbd5c8';g.lineWidth=1;g.beginPath();for(let i=0;i<1300;i++){let [x,y]=at(T+(i-650)/48000),X=w/2+x*w*.43,Y=h/2-y*h*.43;i?g.lineTo(X,Y):g.moveTo(X,Y)}g.stroke()}seed();compile();draw();